# Generated by Django 5.2.1 on 2025-05-21 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Film',
        ),
    ]
